var ACCfg = {};

// permission
ACCfg.PERMISSION_ADMIN = 0;
ACCfg.PERMISSION_USER = 1;

// status: blocked or normal
ACCfg.ACCOUNT_STATUS_UNVERIFIED_ACTIVE = -1;
ACCfg.ACCOUNT_STATUS_VERIFIED_ACTIVE = 0;
ACCfg.ACCOUNT_STATUS_UNVERIFIED_BLOCKED = 1;
ACCfg.ACCOUNT_STATUS_VERIFIED_BLOCKED = 2;

ACCfg.SALT_ROUNDS = 10;

module.exports = ACCfg;